version: '3'

services:
  db:
    image: mysql
    env_file:
      - ./.env
    container_name: db

  backend:
    build: 
      context: ./spring-backend
      dockerfile: Dockerfile
    image: backend-image
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: backend

  frontend:
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile
    image: frontend-image
    volumes:
      - ./nginx-frontend/nginx.conf:/etc/nginx/nginx.conf
    env_file: ./react-frontend/.env
    container_name: frontend
    depends_on:
      - backend

  nginx-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:9000"
    depends_on:
      - frontend
      - backend
    